### ISSUE TITLE
华为7.0 打开手电筒 崩溃

### ISSUE THREAD

**Issue by 1227228155** [maning0303/ZXingCodeDemo#13]

**Comment by 1227228155** [comment]
java.lang.RuntimeException: setParameters failed
        at android.hardware.Camera.native_setParameters(Native Method)
        at android.hardware.Camera.setParameters(Camera.java:2586)
        at com.google.zxing.client.android.camera.CameraManager.openLight(CameraManager.java:174)
        at com.google.zxing.client.android.CaptureActivity$1.onClick(CaptureActivity.java:142)
        at android.view.View.performClick(View.java:5647)
        at android.view.View$PerformClick.run(View.java:22479)
        at android.os.Handler.handleCallback(Handler.java:761)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at android.os.Looper.loop(Looper.java:156)
        at android.app.ActivityThread.main(ActivityThread.java:6623)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
