### ISSUE TITLE
不能识别云端图片

### ISSUE THREAD

**Issue by huangxdan** [maning0303/ZXingCodeDemo#28]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=10010, result=-1, data=Intent { flg=0x1 hwFlg=0x10 (has extras) }} to activity {com.special.pcxinmi/com.google.zxing.client.android.CaptureActivity}: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []
        at android.app.ActivityThread.deliverResults(ActivityThread.java:5782)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:5823)
        at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2613)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:219)
        at android.app.ActivityThread.main(ActivityThread.java:8668)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
     Caused by: java.lang.IllegalArgumentException: column '_data' does not exist. Available columns: []

**Comment by maning0303** [comment]
麻烦请问，这里云端图片什么意思？错误如何产生的？
